aquarist-labs/aquarium

src/glass/angular.json
src/glass/src/app/pages/deployment-page/deployment-page.component.ts

Poll the backend for devices because
only one call is not sufficient.

glass: poll for storage devices

---

src/gravel/__init__.py
src/gravel/api/status.py
src/gravel/controllers/bootstrap.py
src/gravel/controllers/gstate.py
src/gravel/controllers/resources/inventory.py
src/gravel/controllers/resources/storage.py
src/gravel/controllers/services.py
src/gravel/controllers/tests/test_config.py

Fix unit tests failures caused by a98714d and 2b8480b

gravel: fix unit test regressions

---

src/aquarium.py
src/tox.ini

revert of a98714d missed the aquarium module

aquarium: fixup partial revert (e08060e)

---

src/aquarium.py

gravel: fix regression introduced by 9289ce3

---

src/glass/src/app/pages/welcome-page/welcome-page.component.scss

glass: Modify color of link on welcome page

---

.gitignore
src/glass/.eslintrc.json
src/glass/src/app/shared/services/api/services.service.spec.ts
src/glass/src/app/shared/services/notification.service.spec.ts
src/glass/src/app/shared/services/notification.service.ts

- Make 'config' parameter optional
- Add unit tests

glass: Improve notification service

---

src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.html
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.scss
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.spec.ts
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.ts
src/glass/src/app/pages/deployment-page/choose-devices-modal/choose-devices-modal.component.spec.ts
src/glass/src/app/pages/deployment-page/deployment-page.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/pipes/bytes-to-size.pipe.ts
src/glass/src/app/shared/services/notification.service.spec.ts
src/glass/src/app/shared/services/notification.service.ts
src/gravel/controllers/resources/storage.py

Polish the code and UI look.
- Use Angular Reactive Forms
- Introduce validator to take care about the `over-budget`

glass: Cleanup cephfs installer page

---

src/glass/src/app/shared/services/api/orch.service.ts

Use the inventory API call to list all volumes on dashboard.

glass: Use inventory

---

src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.ts
src/glass/src/app/shared/services/api/status.service.ts
src/gravel/api/status.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/cephfs.py
src/gravel/controllers/orch/models.py
src/gravel/controllers/orch/orchestrator.py

gravel/glass: show real health status on dashboard

---

src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.ts
src/glass/src/app/pages/deployment-page/choose-devices-modal/choose-devices-modal.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/services/api/services.service.spec.ts
src/glass/src/styles.scss

- Mark the 'OK' button red in the disk assimilation confirmation dialog
- Cleanup HTML code
- Fix absolute path issue from #156.

glass: Cleanup some issues.

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.scss
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.scss
src/glass/src/app/pages/install-mode-page/install-mode-page.component.scss
src/glass/src/app/pages/not-found-page/not-found-page.component.scss
src/glass/src/app/pages/welcome-page/welcome-page.component.scss
src/glass/src/app/shared/services/notification.service.spec.ts
src/glass/src/app/shared/services/notification.service.ts
src/glass/src/styles.scss

- Rename CSS classes 'glass-theme-' to 'glass-color-theme-'

glass: Colorize Create button in CephFS service page

---

README.md

doc: adding extremely important badges to readme

---

src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.html
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.ts
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/components/components.module.ts
src/glass/src/app/shared/components/submit-button/submit-button.component.html
src/glass/src/app/shared/components/submit-button/submit-button.component.spec.ts
src/glass/src/app/shared/components/submit-button/submit-button.component.ts
src/glass/src/app/shared/shared.module.ts

- Always enable the 'Create' button, but abort if the form is pristine or invalid
- Add and use submit-button component

glass: Block UI while deploying service

---

run_aquarium.sh
tools/setup-dev.sh

Fixes a few issues with handling of the python virtual environment.

tools: various venv fixes

---

tools/build-image.sh

tools: do not use which for kiwi-ng to check presence

---

README.md

doc: remove contributors link

---

systemd/aquarium.service

Fixes #102
Signed-off-by: Lars Marowsky-Bree <lmb@suse.com>

systemd: specify full path to uvicorn

---

src/gravel/controllers/config.py
src/gravel/controllers/gstate.py
src/gravel/controllers/resources/inventory.py
src/gravel/controllers/resources/storage.py
src/gravel/controllers/tests/test_config.py

gravel: reduce Ticker boilerplate code

---

src/gravel/controllers/gstate.py
src/gravel/controllers/tests/test_gstate.py

gravel: add some tests for global state

---

code-of-conduct

doc: adding code of conduct

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.spec.ts
src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.ts
src/glass/src/app/shared/components/submit-button/submit-button.component.ts

glass: Immediately block UI if bootstrapping is in progress

---

doc/project-plan/communication-plan.rst
doc/project-plan/project-plan.rst
doc/project-plan/public-release-plan.rst

doc: add comms plan for aquarium

---

doc/project-plan/communication-plan.rst
doc/project-plan/project-plan.rst
doc/project-plan/public-release-plan.rst

doc: comms plan (already approved)

---

src/aquarium.py
src/gravel/cephadm/models.py
src/gravel/cephadm/tests/outputs.py
src/gravel/cephadm/tests/test_cephadm.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/tests/outputs.py
src/gravel/controllers/orch/tests/test_ceph.py
src/gravel/controllers/resources/storage.py
src/gravel/controllers/services.py
src/gravel/controllers/tests/test_config.py
src/gravel/controllers/tests/test_services.py

gravel: test cephadm wrapper

---

run_aquarium.sh

If we are running inside the microOS image, we may want to run with
system dependencies instead of a virtualenv. Allow specifying that,
while keeping the default behavior reliant on a venv.

run_aquarium.sh: allow running with system deps

---

tools/setup-dev.sh

tools/setup-dev: btrfsprogs are needed for kiwi image

---

tools/build-image.sh

tools: add error_exit and usage_error_exit

---

README.md
doc/project-plan/project-plan.rst
doc/project-plan/public-release-plan.rst

doc: some minor doc tweaks

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.spec.ts
src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.ts
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/services/poll.service.spec.ts
src/glass/src/app/shared/services/poll.service.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/185

glass: add poll service

---

doc/project-plan/communication-plan.rst
doc/project-plan/project-plan.rst
doc/project-plan/public-release-plan.rst

doc: adjusting milestone dates

---

src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts

glass: dashboard: make cpu load a percentage

---

src/glass/src/app/shared/services/status-route-guard.service.ts

... to prevent endless routing loop.

glass: Fix route guard

---

src/glass/src/app/core/navigation-bar/navigation-bar.component.html
src/glass/src/app/core/navigation-bar/navigation-bar.component.scss
src/glass/src/app/core/navigation-bar/navigation-bar.component.spec.ts
src/glass/src/app/material.modules.ts
src/glass/src/defaults.scss
src/glass/src/styles.scss

Fixes: https://github.com/aquarist-labs/aquarium/issues/30

glass: add basic sidenav

---

doc/from-zero-to-hacking.md
src/requirements.txt
tools/setup-dev.sh

Some updates to the getting started guide.
I think there's more to come, but hopefully this is already helpful.

doc: update getting started guide and process

---

src/glass/src/app/pages/deployment-page/deployment-page.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/services/api/bootstrap.service.ts
src/gravel/api/bootstrap.py
src/gravel/controllers/bootstrap.py

Once we finish deploying services, ensure we mark the deployment as finished.
Resolves #205 

gravel/glass: mark deployment ready once we finish deploying services

---

src/glass/src/app/core/navigation-bar/navigation-bar.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html

glass: Change icons

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.spec.ts

Adapt unit test to previous code changes.

---

CONTRIBUTING.md

doc: prefer Fixes: over Closes: in commit messages

---

tools/build-image.sh

tools/build-image.sh: s/btrfstools/btrfsprogs

---

src/glass/src/app/shared/services/status-route-guard.service.spec.ts
src/glass/src/app/shared/services/status-route-guard.service.ts

glass: Adapt unit test to previous code changes

---

src/glass/src/app/core/dashboard/widgets/abstract-dashboard-widget.ts
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.ts
src/glass/src/app/material.modules.ts
src/glass/src/app/pages/deployment-page/deployment-page.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/components/components.module.ts
src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/models/datatable-column.type.ts

Examples:
Fixes: https://github.com/aquarist-labs/aquarium/issues/254

glass: Introduce a datatable component

---

tools/setup-dev.sh

Allow the setup script to run in Debian10 environment.

Adding Debian10 support for the setup script

---

images/microOS/config.xml
tools/build-image.sh

microOS: build other image types besides Vagrant's

---

doc/spec/hackweek-proposal.md

doc: adding hackweek proposal

---

doc/project-plan/public-release-plan.rst

doc: adding dates for comms release

---

.wasser/config.yaml

add config for testing the PR using wasser

---

tools/setup-dev.sh

tumbleweed: not sure why build-image needs kpartx

---

tools/build-image.sh
tools/setup-dev.sh

Replacing the old PR #272  altogether. 
Signed-off-by: AvengerMoJo Alex <alau@suse.com>

Add kiwi boxbuild for distro other then openSUSE

---

src/gravel/api/services.py
src/gravel/controllers/services.py

gravel: api/services: available space must account for reservations

---

src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/orch/ceph.py
src/gravel/tests/conftest.py
src/gravel/tests/unit/controllers/orch/test_ceph.py

gravel: allow creating pools with one replica

---

README.md

doc: small fixes to readme

---

.wasser/config.yaml
tests/vagrant/Vagrantfile.tmpl

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

.wasser/config: use same routine for Leap and Tumbleweed

---

src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/shared/components/widget/widget.component.html
src/glass/src/app/shared/components/widget/widget.component.ts
src/glass/src/app/shared/services/dialog.service.spec.ts
src/glass/src/app/shared/services/dialog.service.ts

glass: Add CephFs share in bootstrapped cluster

---

src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/300

glass: Change colors in capacity widget

---

src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/299

glass: Show the health status textuel

---

src/gravel/controllers/bootstrap.py
src/gravel/controllers/nodes/mgr.py

gravel: fix bugs on bootstrap and join

---

tools/setup-dev.sh

tools: setup-dev.sh: ensure we exit 0 on '--help'

---

.github/workflows/glass-unit-tests.yml

.github/workflows: add glass unit tests config

---

src/gravel/controllers/nodes/messages.py
src/gravel/controllers/nodes/mgr.py

gravel: node/mgr: share ceph.conf and keyring on join

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.ts
src/glass/src/app/shared/services/api/bootstrap.service.ts

glass: Expose bootstrap progress

---

src/aquarium.py
src/gravel/api/nfs.py
src/gravel/controllers/orch/nfs.py

partially resolves #81.
endpoints to manage nfs exports will appear next in a followup PR

gravel: endpoints to manage an nfs service

---

src/gravel/controllers/orch/nfs.py

pending: https://github.com/ceph/ceph/pull/40411

gravel: ctrl/nfs: fixup todo comment

---

tools/aqrdev

Lists the status of existing deployments.

aqrdev: add 'status' command

---

src/glass/src/app/shared/pipes/bytes-to-size.pipe.ts

glass: round size values to 2 decimals if needed

---

src/gravel/api/services.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/cephfs.py
src/gravel/controllers/orch/models.py
src/gravel/controllers/services.py

gravel: expose cephfs credentials via API

---

src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts

glass: Only show widgets with graphs

---

src/gravel/api/nfs.py
src/gravel/controllers/orch/nfs.py

gravel: endpoints to manage nfs exports

---

src/glass/src/styles.scss

glass: Rename CSS class name

---

src/gravel/controllers/services.py

create a cephfs, nfs service, and nfs export under a single svc
Resolves: #82

gravel: ctrl/services: add NFS service create

---

src/glass/package-lock.json
src/glass/package.json
src/glass/patches/@swimlane+ngx-charts+17.0.1.patch

Fixes: https://github.com/aquarist-labs/aquarium/issues/373

glass: Fix ngx-charts library locally

---

src/glass/src/app/core/modals/cephfs/cephfs-modal.component.html
src/glass/src/app/core/modals/cephfs/cephfs-modal.component.ts
src/glass/src/app/pages/services-page/services-page.component.html

* glass: rename CephFS menu item: Rename the `CephFS Share` menu item into `CephFS Service` to keep consistency.
* glass: add missing translation markers in CephFS dialog
* glass: add missing license header

glass: fix cephfs dialog issues

---

src/glass/.htmllintrc
src/glass/src/app/core/core.module.ts
src/glass/src/app/core/modals/cephfs/cephfs-modal.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.spec.ts
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.ts
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/components/dialog/dialog.component.html
src/glass/src/app/shared/components/dialog/dialog.component.ts
src/glass/src/app/shared/models/datatable-action-item.type.ts
src/glass/src/app/shared/models/datatable-data.type.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts
src/glass/src/app/shared/services/api/cephfs.service.spec.ts
src/glass/src/app/shared/services/api/cephfs.service.ts
src/glass/src/app/shared/services/dialog.service.ts

- Add action column to datatable
- Display the CephFs authentication info
- Add cephfsService service
- Add glass-declarative-form component

glass: Display cephfs auth credentials

---

src/glass/src/app/app-routing.module.ts
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/core/modals/nfs/nfs-modal.component.html
src/glass/src/app/core/navigation-bar/navigation-bar.component.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.html
src/glass/src/app/pages/hosts-page/hosts-page.component.scss
src/glass/src/app/pages/hosts-page/hosts-page.component.spec.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts
src/glass/src/app/shared/services/api/nodes.service.spec.ts
src/glass/src/app/shared/services/api/nodes.service.ts
src/glass/src/app/shared/services/status-route-guard.service.ts

- Add 'Hosts' page.
- Add button on this page to show the token that is required to join a new node.
- Add auto-reload feature to datatable component.

glass: Show token required to join new node

---

.github/pull_request_template.md

.github: add pull request template

---

doc/bug-triage.rst

doc: Adding bug triage details doc

---

src/glass/src/app/pages/hosts-page/hosts-page.component.html
src/glass/src/app/pages/hosts-page/hosts-page.component.spec.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/services-page/services-page.component.html
src/glass/src/app/pages/services-page/services-page.component.spec.ts
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts

- Display the Linux CLI command line to mount a CephFS file system.
- Fix bug in datatable.
---
<details>
</details>

glass: Display CephFS mount command

---

src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts

- Add menu entry to dashboard widget.
- Adapt wording of drop-down menu to the 'Services' page.
---
<details>
</details>

glass: Add NFS creation support to dashboard widget

---

src/glass/src/app/core/modals/cephfs/cephfs-modal.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/core/modals/nfs/nfs-modal.component.html
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts
src/glass/src/styles.scss

- Align buttons on the right side in the NFS modal dialog
- Some code cleanup
- Add 'class' property to declarative form field type.
- Render the auth token using 'monospaced' font, so O and zeros should be better visible.
- Render the mount command using 'monospaced' font.
---
<details>
</details>

glass: Do some cleanup

---

src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.ts

Additionally improve the loadData implementation.
---
<details>
</details>

glass: Add unit test for services capacity widget

---

.wasser/config.yaml

Dump aquarium service logs before checking status

---

CONTRIBUTING.md

doc: Mention `jenkins run ...` in CONTRIBUTING.md

---

src/glass/src/app/core/modals/cephfs/cephfs-modal.component.html
src/glass/src/app/core/modals/cephfs/cephfs-modal.component.ts
src/glass/src/app/core/modals/nfs/nfs-modal.component.html
src/glass/src/app/core/modals/nfs/nfs-modal.component.ts
src/glass/src/app/shared/forms/validators.spec.ts
src/glass/src/app/shared/forms/validators.ts
src/glass/src/app/shared/services/api/services.service.ts
src/gravel/api/services.py

glass: add unique service name validation

---

src/gravel/controllers/gstate.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/services.py
src/gravel/tests/conftest.py
src/gravel/tests/unit/controllers/test_gstate.py

gravel: remove cruft, move kvstore to gstate

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.scss
src/glass/src/app/pages/deployment-page/deployment-page.component.scss
src/glass/src/app/pages/install-config-page/install-config-page.component.scss
src/glass/src/app/pages/install-mode-page/install-mode-page.component.scss
src/glass/src/app/pages/not-found-page/not-found-page.component.scss
src/glass/src/app/pages/register-page/register-page.component.scss
src/glass/src/app/pages/welcome-page/welcome-page.component.scss

Update the background image paths in order to prevent them from being hashed during production build.
Fixes: https://github.com/aquarist-labs/aquarium/issues/407
---
<details>
</details>

glass: update background image paths

---

src/glass/src/app/shared/components/widget/widget.component.ts

- use 'take' RxJS operator to automatically unsubscribe the subscription.
- use RxJS 'timer' instead of setTimeout. This way it is easier to handle situations where the component is destroyed before the timer has been fired.
- unsubscribe subscriptions on component destruction. This way situations are handled where the subscription is done but has not been completed before the component is destroyed. Same applies to the timer subscription. It unsubscribes automatically after it has been fired once (thanks to 'take') and the component will unsubscribe if the component is destroyed before the timer has been finished.
---
<details>
- …

glass: Make sure all subscriptions are handled correctly

---

doc/project-plan/project-plan.rst

doc: project-plan/project-plan.rst adjust Milestone 3 date
Signed-off-by: Holger <holgi@suse.com>

Adjust Milestone 3 date

---

images/microOS/config.sh
src/requirements.txt

And fix to a specific sha instead of a branch name.

requirements: use aquarist-labs's aetcd3 fork

---

tools/aqrdev

tools/aqrdev: drop python3.8 specific things

---

src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.scss
src/glass/src/app/shared/components/widget/widget.component.scss

Before:
After:
Fixes: https://github.com/aquarist-labs/aquarium/issues/391
---
<details>
</details>

glass: Refactor dashboard implementation, use masonry style

---

src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/411
---
<details>
</details>

glass: Copy to clipboard does not work in prod build

---

src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/styles.scss

* Add link to website
* Add link to discussions
Related to: https://github.com/aquarist-labs/aquarist-labs.github.io/issues/14
---
<details>
</details>

glass: Add help button to top-bar

---

src/glass/package-lock.json
src/glass/package.json
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.scss
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/shared/components/widget/widget.component.html
src/glass/src/app/shared/components/widget/widget.component.scss
src/glass/src/app/shared/models/dashboard-widget.model.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/302
---
<details>
</details>

glass: Make order of widgets configurable

---

src/glass/src/app/core/top-bar/top-bar.component.html

glass: Use official website URL

---

src/glass/src/app/pages/services-page/services-page.component.ts

glass: Show mount command for NFS services

---

images/microOS/disk.sh
tools/build-image.sh

images: bundle containers

---

src/glass/src/app/pages/install-wizard-page/install-wizard-page.component.html
src/glass/src/app/pages/install-wizard-page/install-wizard-page.component.ts

The installer has not marked the bootstrapping as finished.
---
<details>
</details>

glass: Finish deployment

---

src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.scss

Fixes: https://github.com/aquarist-labs/aquarium/issues/454
---
<details>
</details>

glass: service capacity widget improvement

---

src/glass/src/app/pages/install-wizard-page/steps/services-step/services-step.component.scss

This PR will fix a bug in the Material expansion panel, see https://github.com/angular/components/issues/10024.
Fixes: https://github.com/aquarist-labs/aquarium/issues/461
---
<details>
</details>

glass: service creation expansion panel description

---

src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.scss

In case of an error, the Widget component is responsible for rendering the correct style. The removed CSS code is not applied anymore.
---
<details>
</details>

glass: Remove useless CSS code

---

src/glass/src/app/pages/install-wizard-page/install-wizard-page.component.ts
src/glass/src/app/pages/install-wizard-page/steps/networking-step/networking-step.component.scss
src/glass/src/app/pages/install-wizard-page/steps/services-step/services-step.component.html

- Handle error in Wizard component
- Remove useless class
- Mark the selected NTP config
Fixes: https://github.com/aquarist-labs/aquarium/issues/472
---
<details>
</details>

glass: Fix various issues in installer

---

src/glass/src/setupJest.ts

Fix "Import setup jest file via `import 'jest-preset-angular';` is deprecated and will be removed in v9.0.0"
---
<details>
</details>

glass: fix jest deprecation warning

---

src/gravel/controllers/config.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/inventory.py
src/gravel/controllers/resources/inventory_sub.py
src/gravel/tests/unit/controllers/resources/test_inventory.py

gravel: fix inventory gathering, and speed up device probing

---

src/.coveragerc
src/requirements-test.txt
src/tox.ini

```
----------- coverage: platform linux, python 3.8.9-final-0 -----------
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
gravel/cephadm/cephadm.py                      93     34    63%
gravel/cephadm/models.py                      118      0   100%
gravel/controllers/config.py                   63      0   100%
gravel/controllers/errors.py                    8      3    62%
gravel/controllers/gstate.py                  116     39    66%
gravel/controllers/kv.py                       76     46    39%
gravel/controllers/nodes/bootstrap.py          83     45    46%
gravel/controllers/nodes/conn.py               81     38    53%
gravel/controllers/nodes/deployment.py        208    124    40% …
```

gravel: add pytest coverage report

---

src/gravel/tests/conftest.py
src/gravel/tests/unit/cephadm/test_cephadm.py
src/gravel/tests/unit/controllers/orch/test_ceph.py
src/gravel/tests/unit/controllers/test_config.py
src/gravel/tests/unit/controllers/test_gstate.py
src/gravel/tests/unit/controllers/test_services.py

gravel/tests: add missing type hints

---

doc/from-zero-to-hacking.md

Update the doc to include pyenv in setup script. 
Fixes: [#440]
Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>

[doc]: update doc for python3.8 and pyenv for issue [#440]

---

doc/from-zero-to-hacking.md
doc/project-plan/project-plan.rst
doc/project-plan/roadmap.rst

docs/project-plan: add roadmap and updated milestones

---

src/glass/src/app/shared/components/declarative-form/declarative-form.component.html

The icon was rendered too big.
Before:
After:
---
<details>
</details>

glass: Fix form field suffix

---

.wasser/config-ubuntu.yaml
.wasser/config.yaml
tools/build-image.sh
tools/libaqr/images.py
tools/setup-dev.sh

Multiple fixes in order to make ubuntu development host testable.
---
<details>
</details>

wasser: add ubuntu config

---

src/glass/angular.json
src/glass/package-lock.json
src/glass/package.json
src/glass/src/app/app.module.ts
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.spec.ts
src/glass/src/app/core/modals/file-service/file-service-modal.component.spec.ts
src/glass/src/app/material.modules.ts
src/glass/src/app/pages/install-register-page/install-register-page.component.spec.ts
src/glass/src/app/pages/install-wizard-page/install-wizard-page.component.spec.ts
src/glass/src/app/pages/install-wizard-page/steps/devices-step/devices-step.component.spec.ts
src/glass/src/app/pages/install-wizard-page/steps/host-details-step/host-details-step.component.spec.ts
src/glass/src/app/shared/components/declarative-form/declarative-form.component.spec.ts
src/glass/src/app/shared/services/http-error-interceptor.service.spec.ts
src/glass/src/app/shared/services/notification.service.spec.ts
src/glass/src/app/shared/services/notification.service.ts
src/glass/src/defaults.scss
src/glass/src/styles.scss

Fixes: https://github.com/aquarist-labs/aquarium/issues/478
---
<details>
</details>

glass: Replace notification library

---

.github/workflows/tox.yml
README.md
src/tox.ini

* upload pytest coverage report to https://app.codecov.io/gh/aquarist-labs/aquarium
* add codecov report to PRs
* add codecov badge to the README
---
<details>
</details>

gravel: add codecov report to PRs

---

src/glass/src/app/shared/components/declarative-form/declarative-form.component.ts

glass: Use Material CDK to copy to clipboard

---

src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/allocations-dashboard-widget/allocations-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/allocations-dashboard-widget/allocations-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/allocations-dashboard-widget/allocations-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/core/modals/file-service/file-service-modal.component.html
src/glass/src/app/core/modals/file-service/file-service-modal.component.ts
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/pages/install-wizard/steps/services-step/services-step.component.html
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/services/api/services.service.ts
src/gravel/controllers/services.py
src/gravel/tests/unit/controllers/test_services.py

gravel/glass: rename 'reservation' to 'allocation', reflect change on widget

---

.wasser/config.yaml

wasser: add extra check for aquarium service is running

---

src/glass/src/app/material.modules.ts
src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.html
src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
src/glass/src/styles.scss

Fixes: https://github.com/aquarist-labs/aquarium/issues/475
---
<details>
</details>

glass/gravel: expose ceph-volume device availability

---

src/glass/src/app/shared/components/token-input/token-input.component.ts

The token input control does not show the error message when the field is not touched. This behavior is not correct and is fixed by this PR.
Before:
After:
---
<details>
</details>

glass: Fix error state issue in token control

---

src/glass/src/app/core/modals/file-service/file-service-modal.component.html
src/glass/src/app/core/modals/file-service/file-service-modal.component.spec.ts
src/glass/src/app/core/modals/file-service/file-service-modal.component.ts
src/glass/src/app/functions.helper.spec.ts
src/glass/src/app/functions.helper.ts
src/glass/src/app/i18n.helper.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/432
---
<details>
</details>

glass: allow entering service's required capacity with keyboard, in addition to slider

---

src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.html

Before:
After:
---
<details>
</details>

glass: Remove duplicate subtitle in forms.

---

src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.html
src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
src/glass/src/app/shared/services/api/nodes.service.spec.ts
src/glass/src/app/shared/services/api/nodes.service.ts
src/gravel/api/nodes.py

Instead of just showing the list of available devices, show instead the proposed solution.

glass: show disk solution during installer

---

images/aquarium/config.sh
images/aquarium/config.xml

Otherwise we might end up with mismatches in behavior as pip packages
get updated.
Resolves #544

image: fix dependencies at dev versions

---

src/gravel/controllers/nodes/mgr.py
src/gravel/tests/unit/controllers/nodes/test_mgr.py

gravel: tests: test mgr postbootstrap config 

---

tools/setup-dev.sh

The xUbuntu 20.04 cannot be found at download.opensuse.org
---
<details>
</details>

tools/setup-dev: xUbuntu 20.04 => 20.10 repo

---

images/aquarium/root/etc/motd.template

tools: Fix typo in MOTD (message of the day) template

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.ts
src/glass/src/app/shared/services/api/cephfs.service.spec.ts
src/glass/src/app/shared/services/api/nodes.service.spec.ts
src/glass/src/app/shared/services/api/nodes.service.ts
src/glass/src/app/shared/services/api/orch.service.spec.ts
src/glass/src/app/shared/services/api/orch.service.ts
src/gravel/api/nodes.py
src/gravel/api/orch.py
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/errors.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/nodes/ntp.py
src/gravel/controllers/orch/system.py
src/gravel/tests/unit/controllers/nodes/test_deployment.py

gravel/glass: NTP configuration follower nodes

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.html
src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.ts
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.html
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.ts
src/glass/src/app/pages/install-wizard/steps/hostname-step/hostname-step.component.ts
src/glass/src/app/shared/components/components.module.ts
src/glass/src/app/shared/components/declarative-form/declarative-form.component.html
src/glass/src/app/shared/directives/autofocus.directive.spec.ts
src/glass/src/app/shared/directives/autofocus.directive.ts
src/glass/src/app/shared/directives/directives.module.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts
src/glass/src/app/shared/shared.module.ts

- Add 'autofocus' directive
- Auto-focus hostname field in install wizard
---
<details>
</details>

glass: Add 'autofocus' directive

---

src/glass/src/app/shared/services/api/nodes.service.ts
src/glass/src/app/shared/services/api/orch.service.ts

glass: fix 2 minor linting issues

---

src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.html
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.ts

glass: add devices step to join wizzard

---

doc/from-zero-to-hacking.md
tools/run_aquarium.sh

tools: move run_aquarium.sh to tools

---

images/aquarium/config.xml

image: cleanup, drop ignition and combustion

---

images/aquarium/config.xml

images: turn 'self-install' into a ramdisk

---

doc/project-plan/testing-plan.rst

This is from our discussion:
https://github.com/aquarist-labs/forum/discussions/16
This is just the initial doc, improvements and expansion should be done as followup commits.

docs: Add in draft testing plan

---

doc/from-zero-to-hacking.md

doc: add CLI access

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.ts
src/glass/src/app/shared/services/api/nodes.service.ts

Show the reason why the deployment can not be started.
---
<details>
</details>

glass: Improve error message.

---

COPYING
README.md

aquarium: reflect reality, license under GPL3

---

README.md
doc/from-zero-to-hero.md
doc/spec/hackweek-proposal.md

doc/f02h: we need to rename "hacking" to "hero"

---

.gitignore
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/disks.py
src/gravel/controllers/nodes/host.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/nodes/systemdisk.py
src/gravel/tests/conftest.py
src/gravel/tests/unit/asyncio.py
src/gravel/tests/unit/controllers/nodes/data/hosts.raw
src/gravel/tests/unit/controllers/nodes/data/inventory_basic.json
src/gravel/tests/unit/controllers/nodes/data/mounts_silly.raw
src/gravel/tests/unit/controllers/nodes/data/mounts_with_aquarium.raw
src/gravel/tests/unit/controllers/nodes/data/mounts_without_aquarium.raw
src/gravel/tests/unit/controllers/nodes/test_deployment.py
src/gravel/tests/unit/controllers/nodes/test_disks.py
src/gravel/tests/unit/controllers/nodes/test_etcd.py
src/gravel/tests/unit/controllers/nodes/test_host.py
src/gravel/tests/unit/controllers/nodes/test_mgr.py
src/gravel/tests/unit/controllers/nodes/test_systemdisk.py
src/gravel/tests/unit/controllers/resources/data/inventory_basic.json
src/gravel/tests/unit/controllers/resources/test_inventory.py
src/gravel/tests/unit/controllers/test_services.py
src/gravel/tests/unit/controllers/test_utils.py

gravel: increase test coverage

---

.wasser/config-ubuntu.yaml
images/aquarium/config.sh
images/aquarium/config.xml
src/requirements.txt
tools/build-image.sh
tools/setup-dev.sh

Replace the kiwi package install with pip instead. 
Update the config.sh remove baseCleanMount replace the vagrant setup with baseVagrantSetup
Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>

[tool] Remove repo install kiwi with pip for Debian and Ubuntu also update config.sh

---

images/aquarium/config.xml
tools/aqrdev
tools/libaqr/deployment.py
tools/libaqr/images.py
tools/libaqr/runner.py
tools/libaqr/vagrant.py

Replace the image type with provider type, adding functions to libaqr to include provider type to support virtualbox.
Update the kiwi image with vagrant user and profile to better support multiple provider situtation
All the update should not affect the usage and now the box list and image list will able to list with the provider type. 
Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>
Signed-off-by: Marcel Lauhoff <marcel.lauhoff@suse.com>

[tools] Aqrdev add VirtualBox support

---

tools/aqrtest.py
tools/libaqr/http.py

- Add authenticate support to smoke tests
- Add option to aqrtest.py to skip adding the Vagrant image
---
<details>
</details>

[tools] Add authentication support to smoke tests

---

tools/aqrdev
tools/libaqr/deployment.py

Multiple aqrdev fixes

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.html
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.html
src/glass/src/app/pages/install-wizard/steps/hostname-step/hostname-step.component.ts
src/glass/src/app/pages/install-wizard/steps/ntp-step/ntp-step.component.ts
src/glass/src/app/pages/install-wizard/steps/registration-step/registration-step.component.ts
src/glass/src/app/pages/login-page/login-page.component.html
src/glass/src/app/pages/login-page/login-page.component.scss
src/glass/src/app/pages/login-page/login-page.component.ts
src/glass/src/app/shared/components/declarative-form/declarative-form.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts
src/glass/src/scss/bootstrap.scss

glass: Switch UI library from Angular Material to Bootstrap [Part 3/x]

---

src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.html
src/glass/src/app/pages/hosts-page/hosts-page.component.scss
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/install-mode-page/install-mode-page.component.scss
src/glass/src/app/pages/users-page/users-page.component.html
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/models/declarative-form-modal-config.type.ts
src/glass/src/app/shared/services/dialog.service.spec.ts
src/glass/src/app/shared/services/dialog.service.ts
src/glass/src/scss/bootstrap.scss

glass: Switch UI library from Angular Material to Bootstrap [Part 4/x]

---

src/glass/src/app/core/core.module.ts
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.spec.ts
src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/app/core/top-bar/top-bar.component.scss
src/glass/src/app/core/top-bar/top-bar.component.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.scss
src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.html
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.html
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/components/alert-panel/alert-panel.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.ts
src/glass/src/app/shared/components/dialog/dialog.component.html
src/glass/src/app/shared/components/dialog/dialog.component.scss
src/glass/src/app/shared/components/dialog/dialog.component.spec.ts
src/glass/src/app/shared/components/dialog/dialog.component.ts
src/glass/src/app/shared/components/language-button/language-button.component.html
src/glass/src/app/shared/enum/icon.enum.ts
src/glass/src/scss/bootstrap.scss

glass: Switch UI library from Angular Material to Bootstrap [Part 5/x]

---

src/glass/src/app/core/layouts/installer-layout/installer-layout.component.html
src/glass/src/app/core/layouts/installer-layout/installer-layout.component.scss
src/glass/src/app/core/layouts/main-layout/main-layout.component.html
src/glass/src/app/core/layouts/main-layout/main-layout.component.scss
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.html
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.scss
src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/app/core/top-bar/top-bar.component.scss
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.scss
src/glass/src/app/pages/hosts-page/hosts-page.component.scss
src/glass/src/app/pages/install-wizard/install-wizard-page.scss
src/glass/src/app/pages/not-found-page/not-found-page.component.html
src/glass/src/app/pages/not-found-page/not-found-page.component.scss
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/pages/users-page/users-page.component.scss
src/glass/src/app/shared/components/language-button/language-button.component.html
src/glass/src/scss/bootstrap.scss
src/glass/src/scss/defaults/_colors.scss

glass: Switch UI library from Angular Material to Bootstrap [Part 6/x]

---

src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.html
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.scss
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.spec.ts
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.ts
src/glass/src/app/core/navigation-bar/navigation-bar.component.html
src/glass/src/app/core/navigation-bar/navigation-bar.component.spec.ts
src/glass/src/app/core/navigation-bar/navigation-bar.component.ts

glass: migrate sidenav from material to bootstrap

---

src/glass/src/app/core/layouts/installer-layout/installer-layout.component.scss
src/glass/src/app/core/layouts/main-layout/main-layout.component.html
src/glass/src/app/core/layouts/main-layout/main-layout.component.scss
src/glass/src/app/core/layouts/main-layout/main-layout.component.ts
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.scss
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.html
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.scss
src/glass/src/app/core/navigation-bar/navigation-bar.component.html
src/glass/src/app/core/navigation-bar/navigation-bar.component.scss
src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/app/core/top-bar/top-bar.component.scss
src/glass/src/app/core/top-bar/top-bar.component.ts
src/glass/src/scss/defaults/_colors.scss
src/glass/src/scss/defaults/_variables.scss

glass: Switch UI library from Angular Material to Bootstrap [Part 7/x]

---

COPYING
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.html
src/glass/src/app/shared/components/language-button/language-button.component.html
src/glass/src/scss/defaults/_colors.scss
src/glass/src/scss/defaults/_fonts.scss
src/glass/src/scss/defaults/_variables.scss
src/glass/src/scss/vendor/_colors.scss
src/glass/src/scss/vendor/_fonts.scss
src/glass/src/scss/vendor/_index.scss
src/glass/src/scss/vendor/_variables.scss

glass: Switch UI library from Angular Material to Bootstrap [Part 9/x]

---

src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.html
src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/components/datatable/datatable.component.scss
src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/models/datatable-column.type.ts
src/glass/src/scss/bootstrap.scss
src/glass/src/testing/unit-test-helper.ts

Adds FixtureHelper class to easily test the DOM which lies inside
Fixture.
---
---
Enhancements:
- Sortable columns
- Equal distribution of columns inside the bootstrap grid system in
order to use all available width
- Columns can be sorted by different property (Fixes sorting problems
with size columns)
- Custom CSS classes can be added
---
<details>
</details>

glass: Enhance the datatable

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.html
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.html
src/glass/src/app/shared/components/alert-panel/alert-panel.component.html
src/glass/src/app/shared/components/alert-panel/alert-panel.component.scss
src/glass/src/app/shared/components/dialog/dialog.component.html
src/glass/src/app/shared/components/dialog/dialog.component.scss
src/glass/src/app/shared/components/token-input/token-input.component.html
src/glass/src/app/shared/components/token-input/token-input.component.scss

... after introducing Bootstrap SCSS modifications suggested by https://materialdesignicons.com/bootstrap.
---
<details>
</details>

Fix various UI issues

---

src/glass/angular.json

glass: increase budgets

---

src/glass/cypress/integration/dive_into_aquarium.js
src/glass/cypress/support/index.ts

glass: Fix E2E test.

---

src/glass/src/app/pages/hosts-page/hosts-page.component.html
src/glass/src/app/pages/users-page/users-page.component.html
src/glass/src/app/shared/components/widget/widget.component.html

glass: Use primary color in progress bar

---

src/glass/.gitignore
src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/app/core/top-bar/top-bar.component.ts
src/glass/src/app/pages/login-page/login-page.component.scss
src/glass/src/app/pages/not-found-page/not-found-page.component.scss
src/glass/src/app/shared/components/dialog/dialog.component.html
src/glass/src/app/shared/components/dialog/dialog.component.ts

Glass: Various improvements

---

images/MicroOS/aquarium_root/etc/sudoers.d/aquarium
images/MicroOS/config.sh
images/MicroOS/config.xml
images/MicroOS/disk.sh
images/MicroOS/root/etc/containers/storage.conf
images/MicroOS/root/etc/motd.template
images/MicroOS/root/etc/ssh/sshd_config.append
images/MicroOS/root/etc/udev/rules.d/10-aqr-nics.rules
images/MicroOS/root/usr/bin/update_motd.sh
images/MicroOS/root/usr/lib/issue.d/10-0S
images/MicroOS/root/usr/lib/systemd/system/aquarium-boot.service
images/MicroOS/root/usr/lib/systemd/system/aquarium.service
images/MicroOS/root/usr/lib/systemd/system/update_motd.service
tools/build-image.sh

Create a new MicroOS image build copy most of the image type from MicroOS but adding Aquarium stuff on top. 
Since I create a new directory with the different kiwi files so we can be working on the old and the new microos image in parallel and merge as needed in the future.

[tool] New Kiwi build to create MicroOS base installation image

---

src/glass/cypress/support/index.ts

glass: make cypress wait for button before clicking

---

src/aquarium.py
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/services/api/user.service.spec.ts
src/glass/src/app/shared/services/api/users.service.ts
src/gravel/api/users.py

Use plural as suggested by best practices.
---
<details>
</details>

gravel/glass: Rename API endpoint

---

src/glass/src/app/shared/components/declarative-form/declarative-form.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts

glass: Add select form field

---

src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/models/datatable-action-item.type.ts

glass: Add support for dividers in datatable action menus

---

src/gravel/api/__init__.py

gravel: Raise exception if token is missing

---

src/glass/src/scss/blockui.scss

glass: Fix the color that is used to block the UI

---

src/gravel/api/nodes.py

gravel: fix typo in /nodes/deployment/start API docs

---

src/glass/src/app/pages/login-page/login-page.component.ts
src/glass/src/app/shared/services/dialog.service.ts

Ensure all open modal dialogs are closed.
---
<details>
</details>

glass: Close all dialogs in the login screen

---

src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.spec.ts
src/glass/src/app/functions.helper.spec.ts
src/glass/src/app/functions.helper.ts
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/components/declarative-form/declarative-form.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.scss
src/glass/src/app/shared/components/declarative-form/declarative-form.component.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts
src/glass/src/app/shared/pipes/bytes-to-size.pipe.spec.ts
src/glass/src/app/shared/pipes/bytes-to-size.pipe.ts
src/glass/src/app/shared/pipes/pipes.module.ts
src/glass/src/app/shared/pipes/to-string.pipe.spec.ts
src/glass/src/app/shared/pipes/to-string.pipe.ts
src/glass/src/app/shared/services/api/users.service.spec.ts
src/glass/src/app/shared/services/api/users.service.ts

- Add callback to declarative form which is called on value changes
- Add 'binary' and 'hidden' form fields
- Add various helper functions
- Add 'checked' property to check radio buttons
- Add ability to configure custom validators
- Change SI units according to IEC, e.g. KB to KiB
- Fix issues related to UsersService::update()
- Add 'toString' pipe to make TypeScript happy
- Add field type 'container' to align form fields in a row
---
<details>
</details>

glass: Enhance declarative form component

---

pyrightconfig.json

For those of us using pyright, ignore a bunch of stuff from indexing and
validation.

aquarium: add pyright config

---

images/builder/Dockerfile

Install the btrfsprogs package in the builder container to fix the following error message when building the Aquarium Vagrant image.
```
[ INFO    ]: 13:23:12 | Precalculating required disk size
[ INFO    ]: 13:23:12 | --> system data with filesystem overhead needs 1390 MB
[ INFO    ]: 13:23:12 | --> legacy bios boot partition adding 2 MB
[ INFO    ]: 13:23:12 | --> spare partition adding 5120 MB
[ INFO    ]: 13:23:12 | --> EFI partition adding 20 MB
[ INFO    ]: 13:23:12 | Using configured disk size: 24576 MB
[ INFO    ]: 13:23:12 | Creating raw disk image /builder/out/aqr-main-20211103.01/_out/project-aquarium.x86_64-16.0.0.raw
[ INFO    ]: 13:23:14 | --> creating EFI CSM(legacy bios) partition
[ INFO    ]: 13:23:16 | --> creating EFI partition
[ INFO    ]: 13:23:18 | --> creating root …
```

tools: Fix package prereqs in builder container

---

src/glass/src/app/core/dashboard/widgets/device-utilization-dashboard-widget/device-utilization-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/device-utilization-dashboard-widget/device-utilization-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/memory-dashboard-widget/memory-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/memory-dashboard-widget/memory-dashboard-widget.component.ts

Check https://github.com/xieziyu/ngx-echarts#directive for more information.
---
<details>
</details>

glass: Update the echart widgets the correct way

---

src/glass/src/app/core/top-bar/top-bar.component.html

glass: Add a shorthand in the topbar to change the user password

---

src/tox.ini

Ignore `gravel/cephadm` in our tox configuration to prevent messages like this:
```
lint installed: black==21.10b0,click==8.0.3,isort==5.10.0,mypy-extensions==0.4.3,pathspec==0.9.0,platformdirs==2.4.0,regex==2021.11.2,tomli==1.2.2,typing-extensions==3.10.0.2
lint run-test-pre: PYTHONHASHSEED='1723414377'
lint run-test: commands[0] | black --check --diff aquarium.py gravel
All done! ✨ 🍰 ✨
67 files would be left unchanged.
lint run-test: commands[1] | isort --check-only --diff aquarium.py gravel
ERROR: /home/vot/git/aquarium/src/gravel/cephadm/cephadm.bin Imports are incorrectly sorted and/or formatted.
--- /home/vot/git/aquarium/src/gravel/cephadm/cephadm.bin:before	2021-11-08 10:52:34.422673
+++ /home/vot/git/aquarium/src/gravel/cephadm/cephadm.bin:after	2021-11-08 16:44:33.527913
@@ …
```

gravel: Ignore gravel/cephadm in tox

---

src/glass/src/app/pages/storage-devices-page/storage-devices-page.component.ts

glass: Format size column properly

---

src/glass/src/app/app-routing.module.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/pages/shutdown-page/shutdown-page.component.html
src/glass/src/app/pages/shutdown-page/shutdown-page.component.scss
src/glass/src/app/pages/shutdown-page/shutdown-page.component.spec.ts
src/glass/src/app/pages/shutdown-page/shutdown-page.component.ts
src/glass/src/app/shared/components/dialog/dialog.component.ts
src/glass/src/app/shared/services/api/local.service.ts
src/gravel/api/local.py

Note: This PR can't be tested right now because the Vagrant box is in an unknown state after reboot. The fix for this behaviour is currently in progress.
---
<details>
</details>

gravel/glass: Reboot and shutdown the system

---

images/aquarium/config.sh

image: fix microos config.xml according to upstream

---

src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/models/datatable-column.type.ts

glass: add row selection to datatable

---

src/glass/jest.config.js
src/glass/package.json

See https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy
---
<details>
</details>

Use JS based Jest configuration to be able to use 'ngcc-jest-processor'

---

src/glass/src/app/shared/forms/validators.spec.ts
src/glass/src/app/shared/forms/validators.ts

glass: allow port on registry address

---

src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/styles.scss

Hide overlapping text in table cells

---

src/glass/src/app/app-routing.module.ts
src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/app/core/top-bar/top-bar.component.ts
src/glass/src/app/pages/empty-page/empty-page.component.spec.ts
src/glass/src/app/pages/empty-page/empty-page.component.ts
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/shared/services/api/status.service.ts
src/gravel/controllers/ceph/models.py

Make it as easy as possible for the user to switch to the Bubbles UI. Note, the Bubbles UI will not have a button to switch to Aquarium because Bubbles does not know anything about Aquarium.
---
<details>
</details>

glass/gravel: Add button to redirect to Bubbles UI

---

src/glass/src/app/shared/components/declarative-form/declarative-form.component.html
src/glass/src/app/shared/components/declarative-form/declarative-form.component.ts

glass: Do not order select options

---

.wasser/config.yaml

debug: add info about uptime right after reboot

---

tools/requirements.txt

When attempting to build `aquarium` on Ubuntu 20.04, I received the following during `build-image.sh`:
~~~
+ tee /home/tech/aquarium/images/build/aquarium/_logs/aquarium-build.log
[ INFO    ]: 22:58:16 | Reading box plugin config file: /home/tech/aquarium/tools/venv/lib/python3.8/site-packages/kiwi_boxed_plugin/config/kiwi_boxed_plugin.yml
[ DEBUG   ]: 22:58:16 | EXEC: [mkdir -p /home/tech/.kiwi_boxes/tumbleweed]
[ INFO    ]: 22:58:16 | Validating kiwi_build_command_args:
['system', 'build', '--description', '/home/tech/aquarium/images/build/aquarium', '--target-dir', '/home/tech/aquarium/images/build/aquarium/_out']
[ INFO    ]: 22:58:16 | Building with:
['--type', 'oem', '--profile', 'ContainerHost-Vagrant', 'system', 'build', '--description', …

tools: bump `kiwi-boxed-plugin` to 0.2.17

---

doc/from-zero-to-hero.md

Signed-off-by: James McClune <falcon78921@users.noreply.github.com>
---
<details>
</details>

doc: minor nit in from-zero-to-hero guide
