aquarist-labs/aquarium

run_aquarium.sh
src/gravel/controllers/config.py
src/gravel/controllers/tests/test_config.py

Adds environment var `AQUARIUM_CONFIG_DIR=` for specifying a custom
location to the aquarium config files
Resolves: #160 

gravel: add env for custom config path

---

tools/build-image.sh

This is just a minor rearranging of the code to only delete the build directory
if it actually exists, and the clean option was explicitly used.
Signed-off-by: Mike Latimer <mlatimer@suse.com>

images: minor update to cleanup code

---

src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/shared/services/api/services.service.spec.ts

Simple widget to only currently show the name and the type of the share
as some useful information is missing in the current API. It will route
to the deployment page if no service is found.

glass: Services dashboard widget

---

run_aquarium.sh
src/aquarium.py

Automatically inferring where to put the config file is causing a few issues:
1. people get confused as to why the config ends up in a `conf/` directory in the project's root while running in a VM; and
2. running a fresh image with an NFS mount to the repo's root containing a `conf` directory from a previous run would cause all sorts of troubles on the backend (mainly because the state in the config would not match the actual fresh status of the system).
This patchset makes the config location configurable, letting the user do whatever they want, and ensures we can specify it's a new run (via `-n|--new`) to blow away any existing configuration.

run_aquarium.sh: specify config, debug on cli

---

run_aquarium.sh

This will prevent the following error:
```
node01:/srv/aquarium # ./run_aquarium.sh --debug
realpath: missing operand
Try 'realpath --help' for more information.
```

gravel: Add check before calling realpath

---

tools/build-image.sh

'/etc/systemd/system/' -> '/usr/lib/systemd/system/'
Resolves: #190

tools/build-image.sh: move systemd unit dir

---

tools/build-image.sh

tools/build-image.sh: remove etc dir from tar bundle

---

src/glass/src/app/pages/deployment-page/deployment-page.component.ts

Do not only check if there is a HostDevice
object. Do also check (5 times) if any
device is returned by the API.

glass: fix bug when fetching devices

---

src/glass/src/app/app-routing.module.ts

Use a hash in UI URLs, e.g. 'http://localhost:4242/#/installer/create/deployment' to better distinguish between UI URLs and Swagger (http://localhost:4242/api/docs) or REST API (http://localhost:4242/api/status/).

glass: Use a hash in router URLs

---

src/gravel/controllers/config.py
src/gravel/controllers/tests/test_config.py

Test inventory and storage probe intervals, plus the location of the
service state file (storage.json).
This test exposed a bug where the service state file location is not changing
based on parameters passed when initializing the Config object. Pytest reports
the problem as follows:
>       assert config.options.service_state_path == 'foo/storage.json'
E       AssertionError: assert '/etc/aquarium/storage.json' == 'foo/storage.json'
E         - foo/storage.json
E         + /etc/aquarium/storage.json
@mgfritch provided the fix for this issue in controllers/config.py.
Signed-off-by: Mike Latimer <mlatimer@suse.com>

gravel: add unit test for config options

---

src/gravel/controllers/orch/ceph.py

```
Traceback (most recent call last):
File "aquarium/src/gravel/controllers/orch/ceph.py", line 58, in __del__
if self.cluster:
AttributeError: 'Mgr' object has no attribute 'cluster'
```

gravel: fixup pytest warning

---

src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/tests/test_ceph.py

location to the `ceph.conf` file can be passed to the `Ceph` baseclass,
extend this to the Mgr/Mon classes

gravel: pass the ceph.conf file to the Mgr/Mon class

---

tools/build-image.sh

tee is hiding exit code from kiwi-ng correspondingly
does not report about an error

tools: return exit code from kiwi-ng

---

src/glass/package-lock.json
src/glass/package.json
src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.scss
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.scss
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/shared/pipes/relative-date.pipe.spec.ts
src/glass/src/app/shared/pipes/relative-date.pipe.ts
src/glass/src/app/shared/services/api/orch.service.spec.ts
src/glass/src/app/shared/services/api/orch.service.ts
src/glass/src/app/shared/shared.module.ts
src/glass/src/defaults.scss
src/glass/src/styles.scss

- Add a dashboard widget to display the system facts retrieved via /api/orch/facts.
- Enhance 'OrchService' to request facts.
- Add 'relativeDate' pipe.
- Cleanup code of other dashboard widgets.
- Use CSS Grid to render the dashboard widgets instead of Flexbox.
Fixes: https://github.com/aquarist-labs/aquarium/issues/200

glass: Add dashboard widget to display system facts

---

src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/abstract-dashboard-widget.ts
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/hosts-dashboard-widget/hosts-dashboard-widget.component.ts
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/shared/services/api/orch.service.ts
src/gravel/api/orch.py

- Add hosts dashboard widget
- Keep polling data in case of an error
- Refactored response of /orch/hosts
Fixes: https://github.com/aquarist-labs/aquarium/issues/202

glass: Add a host dashboard widget

---

src/gravel/controllers/orch/cephfs.py

It seems the behavior of 'fs volume create' changed beneath us and no
longer outputs any information. Ignore any possible output, and instead
rely solely on its return code.
Resolves #230

gravel: cephfs create: ignore output from mgr call

---

src/aquarium.py
src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.ts
src/glass/src/app/shared/services/api/bootstrap.service.ts
src/glass/src/app/shared/services/api/status.service.ts
src/glass/src/app/shared/services/status-route-guard.service.ts
src/gravel/api/nodes.py
src/gravel/controllers/bootstrap.py
src/gravel/controllers/config.py
src/gravel/controllers/gstate.py
src/gravel/controllers/nodes.py
src/requirements.txt

Please note:
1. Existing deployments will be broken by these changes;
2. There's been a deployment stage format change, and we are now using integers instead of strings for the enum; @votdev mind looking at the glass bits?
3. Currently missing tests because I'm not fully satisfied with the direction, and don't want to be writing and rewriting tests until I'm sure the architecture makes sense.

gravel: initial support for node communication over websockets

---

src/glass/angular.json

Adapt configuration to prevent the message ".../dashboard-page.component.ts depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.".

glass: Fix Angular warning message

---

src/gravel/controllers/tests/test_services.py

Moves unittest mocks into a contextmanager.
Mock patching at the import level causes unintended side effects on other unittests.

gravel: refactor service module unittests

---

tools/build-image.sh

We don't need to be root to check if mkfs.btrfs is present.

tools/build-image.sh: use /sbin/mkfs.btrfs instead of sudo

---

tools/build-image.sh

Everything in images/build/$NAME/_out is owned by root:root, which means normal users can't remove that stuff :-/  I've split the
directory existence check so that in case the `sudo rm` fails (wrong password or whatever), it'll check again for the directory and bail out if it exists.

tools/build-image.sh: Use sudo with --clean

---

tests/vagrant/setup.sh

The first time you run `tests/vagrant/setup.sh`, it adds a new Vagrant box.  That's fine.  But if you later make some changes and build a new image, then run `tests/vagrant/setup.sh` *again*, you end up using the old box, because something with that name already exists.  Let's delete that thing if it exists, so we're always using the latest and greatest.

test/vagrant: Always add new Vagrant box

---

src/glass/src/app/pages/deployment-page/deployment-page.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.ts

Change text from 'Choose selected devices' to 'Deploy devices' because it matches better what happens here.

glass: Change button text

---

src/glass/src/app/core/core.module.ts
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.html
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.scss
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.spec.ts
src/glass/src/app/core/navigation-bar/navigation-bar-item/navigation-bar-item.component.ts
src/glass/src/app/core/navigation-bar/navigation-bar.component.html
src/glass/src/app/core/navigation-bar/navigation-bar.component.scss
src/glass/src/app/core/navigation-bar/navigation-bar.component.ts

Add the possibility to define sub-items in the navigation.
Fixes: https://github.com/aquarist-labs/aquarium/issues/250

glass: improve side-nav (sub-items)

---

tools/setup-dev.sh

Adding Ubuntu20.10 support 
1) Replacing the sed with the os-release file may or may not have quote after ID=
2) swap the order by installing the repo key before adding repo to avoid add-repo update without key. 
Signed-off-by: AvengerMoJo Alex <alau@suse.com>

Adding Ubuntu20.10 setup script support

---

src/glass/src/app/pages/deployment-page/deployment-page.component.html

Change color of the 'next' button to primary color like it is done in chooser step 1 and 3.

glass: Colorize 'Next' button

---

src/glass/src/app/app.module.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.scss

(Re-)Add the padding if no services have been configured.
Fixes: https://github.com/aquarist-labs/aquarium/issues/217

glass: fix padding if no services configured

---

src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts

Before:
After:
- The capacity widget shows incorrect values
- Adapt property names in services widget

glass: Fix various issues in dashboard

---

run_aquarium.sh

Add the command line argument "--port" to run_aquarium.sh to change the port gravel is listening to. Defaults to 1337.

gravel: Add option to configure port via cmd args

---

images/microOS/config.xml
tools/build-image.sh

With this we can now build an image that runs aquarium on start.
Problem so far is: bootstrapping errors out. But this is a start!
Resolves #275 
Signed-off-by: Alex Lau (AvengerMoJo) \<alau@suse.com>

microOS: add live ISO support

---

src/aquarium.py
src/gravel/api/bootstrap.py
src/gravel/api/nodes.py
src/gravel/api/orch.py
src/gravel/api/services.py
src/gravel/api/status.py
src/gravel/cephadm/cephadm.py
src/gravel/cephadm/models.py
src/gravel/controllers/bootstrap.py
src/gravel/controllers/gstate.py
src/gravel/controllers/nodes/conn.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/cephfs.py
src/gravel/controllers/orch/models.py
src/gravel/controllers/orch/orchestrator.py
src/gravel/controllers/resources/inventory.py
src/gravel/controllers/resources/storage.py

With this patchset we are
1. introducing automatic logging to file. The log is currently being placed under `/tmp/aquarium.log`, and it's limited to 10MB.
2. providing an endpoint to obtain the log file.
3. changing a bunch of logging messages to make output not look horrible.
4. relicensing a bunch of files to gplv3

gravel: log to console and file; piggyback and relicense stuff

---

src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts

Do not show node specific dashboard widgets (e.g. system information, volumes) by default.

glass: Hide node specific widgets by default

---

src/glass/src/app/pages/dashboard-page/dashboard-page.component.scss
src/glass/src/app/shared/components/widget/widget.component.scss

The missing CSS causes flex layout to show a scroll bar and renders the widgets with an incorrect padding.

glass: Relocate CSS definition

---

src/glass/src/app/core/dashboard/widgets/health-dashboard-widget/health-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.ts
src/glass/src/app/shared/components/components.module.ts
src/glass/src/app/shared/components/widget/widget.component.html
src/glass/src/app/shared/components/widget/widget.component.scss

Fix issues found during PR review and that couldn't be fixed in that PRs to be able to merge them immediatelly.
- Use padding instead of fixed height in health widget.
- Center icon in widgets that are in error state. Use padding around the icon.
- Translate button text.
- Set CephFS required space to min 1 byte to prevent an error when calling the REST API endpoint. This way the form field will error out when the user does not select a required space, too.
- Execute 'npm run fix'.
- Execute 'npm run lint' and fix issues.

glass: Fix various issues

---

src/aquarium.py
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/volumes-dashboard-widget/volumes-dashboard-widget.component.ts
src/glass/src/app/pages/register-page/register-page.component.ts
src/glass/src/app/shared/services/api/local.service.spec.ts
src/glass/src/app/shared/services/api/local.service.ts
src/glass/src/app/shared/services/api/orch.service.spec.ts
src/glass/src/app/shared/services/api/orch.service.ts
src/glass/src/app/shared/services/api/status.service.spec.ts
src/glass/src/app/shared/services/api/status.service.ts
src/glass/src/app/shared/services/status-route-guard.service.spec.ts
src/glass/src/app/shared/services/status-route-guard.service.ts
src/gravel/api/local.py
src/gravel/api/orch.py
src/gravel/api/status.py
src/gravel/cephadm/cephadm.py
src/gravel/cephadm/models.py
src/gravel/controllers/nodes/mgr.py

With this patchset we change a few things around in the API:
* Introduce a new set of endpoints at `/api/local`, meaning these are endpoints providing information and operations about or on the node where these are being invoked. This ought to reduce confusion about where information is coming from, given these were somewhat spread across the whole API.
* Moved `/orch/volumes`, `/orch/nodeinfo`, `/orch/inventory` to `/local/`.
* Dropped `/orch/facts` altogether.
* Added some API documentation, to be expanded as we go.
* Removed `node_stage` from the result from `/api/status` given we should not mix the node's stage with a more generic _status_.
* Added a `/api/local/status` endpoint, which provides both the current `node_stage`, as well as boolean indicating whether the node has been …

gravel: rework api endpoints, drop some, ensure we can check if node is ready to handle requests

---

src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts

* Change colors in system information widget.
* Use 'Free' and 'Used' instead of 'Unassigned' and 'Assigned' in dashboard widgets because IMO these are more used and easier to understand.
Fixes: https://github.com/aquarist-labs/aquarium/issues/301

glass: Use consistent language in dashboard

---

src/gravel/api/bootstrap.py
src/gravel/cephadm/cephadm.py
src/gravel/controllers/bootstrap.py
src/gravel/tests/unit/cephadm/test_cephadm.py

This is extremely fragile, as we're essentially parsing cephadm's
free-form output and associating each step with a rule of thumbs
percentage. Should cephadm change their messaging, this can easily
break.

gravel: expose bootstrap progress

---

src/glass/src/app/shared/components/widget/widget.component.html
src/glass/src/app/shared/components/widget/widget.component.scss

- The padding was set to the incorrect container
- Relocate the loading progress bar outside the content container and render it with the full size of the widget (to match the Material style).
Before:
After:

glass: Fix widget layout in error state

---

tests/vagrant/Vagrantfile.tmpl

According to the recent docs of vagrant:
host_ip (string) - The IP on the host you want to bind the forwarded port to.
If not specified, it will be bound to every IP. By default, this is empty.
This is not the case for Leap 15.2 where vagrant version is 2.2.7 and
forwarded ports are bound only to localhost ip addresses.
While Tumbleweed has vagrant version 2.2.14 and does not have this
issue.

tests/vagrant: listen all host ips for older vagrant versions

---

src/gravel/cephadm/README.md

Minor tweak to correct the name of the cephadm symlink.
Signed-off-by: Mike Latimer <mlatimer@suse.com>

gravel: cephadm: correct symlink documentation

---

src/gravel/api/services.py
src/gravel/controllers/services.py

handle unknown service types in a generic way, rather than a
cephfs specific way

gravel: simplify unknown service type handling

---

src/glass/src/app/pages/register-page/register-page.component.html
src/glass/src/app/pages/register-page/register-page.component.spec.ts
src/glass/src/app/pages/register-page/register-page.component.ts
src/glass/src/app/shared/forms/validators.spec.ts
src/glass/src/app/shared/forms/validators.ts

Move the IP/FQDN validator to a more centralized place so that it can be used by other components as well.

glass: move the IP/FQDN validator

---

src/aquarium.py
src/gravel/api/devices.py
src/gravel/controllers/config.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/models.py
src/gravel/controllers/resources/devices.py

Provides device information, including utilization (total, avail, used KB, etc), on a per-host basis.
The device information includes device-specific information.
As an example, the output should be similar to this:
```
{
"node01": {
"utilization": {
"total_kb": 33538048,
"avail_kb": 33515012,
"used_kb": 23036,
"utilization": 0.06868616802027358
},
"devices": [
{
"host": "node01",
"osd_id": 0,
"path": "/dev/vdb",
"rotational": true,
"vendor": "0x1af4",
"model": "",
"utilization": {
"total_kb": 8384512,
"avail_kb": 8378720,
"used_kb": 5792,
"utilization": 0.06907975085490962
}
},
...
```

gravel: provide device info, per host, with utilization, via API

---

src/gravel/api/services.py
src/gravel/controllers/resources/storage.py
src/gravel/controllers/services.py

Through an API endpoint at '/services/stats' we will expose a dictionary
of service names to service statistics, including allocated space and
how much space is being used by the service.

gravel: ctrl/services: expose services space usage

---

src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.html
src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.ts
src/glass/src/app/shared/services/poll.service.ts

Before the system can be bootstrapped it must be initialized. This process might take some time. In the meantime the bootstrapping process will not be started.

glass: Check node is initialized before bootstrapping

---

src/tox.ini

gravel: tox: have flake8 ignoring cephadm.bin

---

src/glass/src/app/app-routing.module.ts
src/glass/src/app/core/navigation-bar/navigation-bar.component.ts
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/pages/services-page/services-page.component.html
src/glass/src/app/pages/services-page/services-page.component.scss
src/glass/src/app/pages/services-page/services-page.component.spec.ts
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/pipes/redundancy-level.pipe.ts
src/glass/src/app/shared/services/status-route-guard.service.ts
src/glass/src/app/shared/shared.module.ts

This is the core service page. In follow up PRs the ability to edit/delete them will be added. It is also planned to enhance the visualized data per service.

glass: Add services page

---

src/gravel/controllers/resources/status.py

gravel: ctrl/status: fix typo on variable name

---

src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts

glass: Fix CPU load chart in sys info widget

---

src/gravel/controllers/services.py

Given we obtain storage statistics periodically, it may happen that we
are trying to obtain statistics from a recently created service for
which pools we don't yet have statistics. In that case, skip the pool.
Resolves #346 

gravel: ctrl/svc: ignore missing pool on stats

---

src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.html
src/glass/src/app/pages/deployment-page/cephfs-modal/cephfs-modal.component.ts
src/glass/src/app/shared/services/api/services.service.ts
src/gravel/api/services.py
src/gravel/controllers/resources/devices.py
src/gravel/controllers/services.py

With this patchset we are now able to present certain constraints that are not able to be met when creating a service; e.g., number of hosts doesn't allow for availability in case of failures, or number of replicas cannot be met.
Unfortunately, my skills at showing those constraints on the UI came up short and, to be perfectly frank, it's quite ugly. Hopefully someone else will be able to make them more digestible once this is merged :)
Resolves #86 

gravel/glass: present constraints on service creation

---

src/glass/src/app/app-routing.module.ts
src/glass/src/app/material.modules.ts
src/glass/src/app/pages/bootstrap-page/bootstrap-page.component.html
src/glass/src/app/pages/install-config-page/install-config-page.component.html
src/glass/src/app/pages/install-config-page/install-config-page.component.scss
src/glass/src/app/pages/install-config-page/install-config-page.component.spec.ts
src/glass/src/app/pages/install-config-page/install-config-page.component.ts
src/glass/src/app/pages/install-mode-page/install-mode-page.component.html
src/glass/src/app/pages/pages.module.ts
src/glass/src/app/shared/services/api/orch.service.spec.ts
src/glass/src/app/shared/services/api/orch.service.ts
src/glass/src/defaults.scss
src/gravel/api/orch.py
src/gravel/controllers/orch/ntp.py

- **gravel: add PUT-method to set NTP**: Add a PUT-method to the orch endpoint in order to set the NTP server for a node.
- **glass: add option to configure NTP on initial node**

gravel/glass: add option to configure ntp at initial deployment

---

src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/models.py

When we create a single-node deployment, we should enable the user to have a healthy system out of the box; with that in mind, we must ensure that our replicas are properly replicated across OSDs, instead of the default, hosts.
With this patchset we first ensure that we create a single-node ruleset, and set it as the default for new pools upon bootstrap and before we start creating pools; then we ensure that we reset the default to `replicated_rule` upon join of a new node, as well as adjusting the existing pools' rulesets.
Resolves #103 

gravel: adjust crush rulesets depending on number of nodes

---

src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.ts
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/shared/services/api/services.service.spec.ts
src/glass/src/app/shared/services/api/services.service.ts

Fixes: https://github.com/aquarist-labs/aquarium/issues/344

glass: Add consumed storage by service dashboard widget

---

src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.ts
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts
src/glass/src/app/shared/services/api/status.service.spec.ts
src/glass/src/app/shared/services/api/status.service.ts

This is still a simple widget as time series rates are missing ATM.
Fixes #360

glass: Performance widget

---

src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.ts

- Show only the 'Top 5' services (display size is limited in the widget)
- Embed chart components in div to fix flex layout render issues

glass: Performance dashboard widget cleanup

---

src/gravel/cephadm/models.py
src/gravel/controllers/resources/devices.py

If the LV is not a ceph osd, then we won't have the fields we'd be
expecting out of an osd partition.

gravel: cephadm: lvs may not have osd info

---

src/gravel/controllers/orch/ceph.py
src/gravel/controllers/resources/status.py

We introduced a regression a while ago while fixing a bug, making the status controller tick while a node is joining, which should not happen because, at the time, we don't have a ceph.conf. This patchset fixes this.
Additionally, we're deduplicating some code in the ceph controller.

gravel: fix ctrl/status and deduplicate some code

---

src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/performance-dashboard-widget/performance-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts

Do not use foo.bind(this) in combination with 'valueFormatting', otherwise Angular CD will get confused and assumes false changes.
Fix various issues in the `Performance` dashboard widget:
- Translate title text
- Add workaround to force charts to adapt their size to the parent container. Better approaches are welcome.

glass: Fix dashboard widgets issue related to valueFormatting

---

src/glass/src/app/core/core.module.ts
src/glass/src/app/core/modals/nfs/nfs-modal.component.html
src/glass/src/app/core/modals/nfs/nfs-modal.component.scss
src/glass/src/app/core/modals/nfs/nfs-modal.component.spec.ts
src/glass/src/app/core/modals/nfs/nfs-modal.component.ts
src/glass/src/app/pages/deployment-page/deployment-page.component.html
src/glass/src/app/pages/deployment-page/deployment-page.component.ts
src/glass/src/app/pages/services-page/services-page.component.html
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/services/dialog.service.ts

- glass: add NFS component: Add the component itself and to the dialog service in addition. It's more or less the content of the CephFS dialog at the moment. I would like to take it as a starting point and refactor/extract duplicated content step by step later.
- glass: add NFS component to the installer
- glass: add NFS component to services page

glass: add nfs service

---

src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.html
src/glass/src/app/core/modals/declarative-form/declarative-form-modal.component.ts
src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/shared/models/declarative-form-config.type.ts

Add 'hasCopyToClipboardButton' property. It is used by the 'text' and 'password' fields.

glass: Enhance declarative form modal

---

src/glass/src/app/core/dashboard/widgets/services-dashboard-widget/services-dashboard-widget.component.ts
src/glass/src/app/pages/services-page/services-page.component.ts
src/glass/src/app/shared/components/components.module.ts
src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/pipes/map.pipe.spec.ts
src/glass/src/app/shared/pipes/map.pipe.ts
src/glass/src/app/shared/pipes/pipes.module.ts
src/glass/src/app/shared/pipes/redundancy-level.pipe.spec.ts
src/glass/src/app/shared/pipes/relative-date.pipe.spec.ts
src/glass/src/app/shared/pipes/sort-by.pipe.spec.ts
src/glass/src/app/shared/shared.module.ts

- Add pipes module.
- Add the map pipe and use it in the datatable.
- Use datatable 'map' template in services dashboard widget and page.
Check the `Type` column for example.
Before:
After:
---
<details>
</details>

glass: Add map pipe

---

src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.ts

Utilizations of 0.000006287751370776091 and 0.00004227160129839737 will be rendered as 2 bar charts with different length. This looks weird because effective the value is 0%. Because of that the 'utilization' property will be rounded to 2 decimal places.
Fixes: https://github.com/aquarist-labs/aquarium/issues/383
---
<details>
</details>

glass: service capacity gets weird on 0.0% occupation

---

src/glass/src/app/core/modals/cephfs/cephfs-modal.component.html
src/glass/src/app/core/modals/cephfs/cephfs-modal.component.ts
src/glass/src/app/core/modals/nfs/nfs-modal.component.html
src/glass/src/app/core/modals/nfs/nfs-modal.component.ts

The validators of some fields have not been triggered after the number of replicas was modified.
---
<details>
</details>

glass: Fix validator issue in CephFS and NFS modal dialogs

---

.gitignore
Makefile
images/microOS/config.xml
tools/build-image.sh
tools/setup-dev.sh

I've added a Makefile with a `dist` target, so you can now run `make dist` to get a tarball named something like aquarium-0.1.0-0-g2b6942a.tar.gz, which includes a built glass and all the necessary bits of gravel.
This doesn't change the current dev workflow at all.  You still build an image by running `./tools/build-image.sh`, but that script will in turn call `make dist` to get a tarball to install in the image.
Note: the version string used in the tarball name is based on the latest annotated tag in the form 'vX.Y.Z', which means I've suddenly introduced the notion of version numbers and releases to the project.  Until such time as an actual release is tagged, the version will default to v0.0.0, just to have the build working.
Fixes: https://github.com/aquarist-labs/aquarium/issues/277 …

tools: Add Makefile for building dist tarball

---

src/glass/src/app/shared/services/api/services.service.spec.ts
src/glass/src/app/shared/services/api/services.service.ts
src/gravel/api/services.py

Change the endpoint `/api/services/{service_name}` to `/api/services/get/{service_name}` to prevent calling the endpoint `/api/services/stats` for a service called `stats`.
The issue was introduced by https://github.com/aquarist-labs/aquarium/pull/399.
---
<details>
</details>

glass: Change endpoint name to get a service by name

---

images/microOS/config.sh
images/microOS/config.xml
src/aquarium.py
src/gravel/api/services.py
src/gravel/controllers/config.py
src/gravel/controllers/gstate.py
src/gravel/controllers/kv.py
src/gravel/controllers/nodes/messages.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/status.py
src/gravel/controllers/services.py
src/gravel/typings/aetcd3/__init__.pyi
src/gravel/typings/aetcd3/client.pyi
src/gravel/typings/aetcd3/events.pyi
src/gravel/typings/aetcd3/locks.pyi
src/mypy.ini
src/requirements.txt

We need something to share state across multiple nodes, consistently, and, ideally, without a single point of failure. This patchset proposes etcd as that thing.
Because it exists, is simple enough to setup, and does not require Ceph to work.
We _could_ use the monitors' config-key/kv store, but a few things strike me as good enough reasons not to:
1. That was never what it was supposed to exist for, and everyone keeps abusing it. Ceph needs something like etcd to keep its stuff, or to implement a proper kvstore may it be in the monitors or elsewhere (the manager's would be preferable tbh).
2. We lose the store if the cluster dies, or doesn't start, or a monitor fills up to the brim and causes a quorum loss. If that happens, Aquarium needs to still be available to provide info to the …

gravel: add etcd

---

tools/setup-dev.sh

This ensures we've got at least python 3.8, which is what we use in our images, and is required for asyncio (it's not impossible 3.7 might work, but nobody's tested that so it seems safest to stick with 3.8).
I've also made it a bit more obvious when dependency installation fails.  I've seen cases where zypper fails to refresh some repo, but that scrolls off the top of the screen, the script bails out and all you see at the bottom is the "Nothing to do" line from zypper, so you just assume there's nothing to do.
---
<details>
</details>

tools: setup-dev.sh: check for python >= 3.8

---

src/glass/angular.json

Add 'validator' to the Angular 'allowedCommonJsDependencies' config option to suppress the warning in `prod` build.
---
<details>
</details>

glass: Fix CommonJS warning

---

images/microOS_build_env/Dockerfile

Preinstall 'make' in the openSUSE Leap based MicroOS build environment. The `/tools/build-image.sh` script needs `make` after the [latest changes](https://github.com/aquarist-labs/aquarium/pull/382).
---
<details>
</details>

cli: Add missing package to Docker environment

---

tools/build-image.sh

tools: make kiwi image build failures a bit more obvious

---

src/glass/src/app/app-routing.module.ts
src/glass/src/app/core/core.module.ts
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.html
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.scss
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.spec.ts
src/glass/src/app/core/navigation-bar/breadcrumbs/breadcrumbs.component.ts
src/glass/src/app/core/navigation-bar/navigation-bar.component.ts
src/glass/src/app/core/top-bar/top-bar.component.html
src/glass/src/app/core/top-bar/top-bar.component.spec.ts
src/glass/src/defaults.scss

Picture of the crumbs:
Picture when hovering over an non active crumb:
My intend of the look was that it should looks kind of cool, simple and futuristic but not cheesy at the same time. I'm really not sure about this, but it looked the best out of all approaches and examples of breadcrumbs I looked at.
Fixes #107
---
<details>
</details>

glass: Breadcrumbs

---

images/microOS_build_env/Dockerfile

Switch from Leap top Tumbleweed because of Python 3.8.
---
<details>
</details>

tools: Switch Docker container OS to Tumbleweed

---

tools/setup-dev.sh

python3-rados is only be needed at runtime, in the image. It shouldn't be necessary for this to be installed on the host, and it makes life easier if it's not, when using different python versions via pyenv.
---
<details>
</details>

tools/setup-dev.sh: remove python3-rados dependency

---

.github/workflows/tox.yml
images/microOS/config.sh
src/gravel/controllers/nodes/mgr.py
src/gravel/typings/aetcd3/client.pyi
src/gravel/typings/aetcd3/members.pyi
src/mypy.ini
src/requirements.txt

We had a tiny problem when expanding the cluster: we were providing wrong etcd initial peers to the joining node; instead of using the information provided by aetcd3's `client.add_member()`, we were assuming what those values could be based on our limited knowledge of the cluster. Even though that information was enough to add a second node, it was not enough to add three or more nodes.
Instead, we now rely on additional return from `client.add_member()`, which provides us with a list of existing cluster members, which we then transform into something the joining node can use. The only snafu is that aetcd3, at this point in time, does not support this additional information being returned by said function: we had to patch aetcd3 (and [opened a PR …

gravel: make node join work properly with etcd, drop node roles

---

src/gravel/controllers/orch/ceph.py

instead of str 'true'
---
<details>
</details>

gravel: pass bool to `yes_i_really_mean_it`

---

run_aquarium.sh

On the assumption that run_aquarium.sh is usually run inside the MicroOS image (and not on the dev host), let's default to using
system deps. This commit removes the --with-system-deps option and adds a --use-venv option for cases when using the venv is
desirable.
---
<details>
</details>

run_aquarium.sh: default to running with system deps

---

src/aquarium.py
src/gravel/api/bootstrap.py
src/gravel/api/devices.py
src/gravel/api/local.py
src/gravel/api/nodes.py
src/gravel/api/services.py
src/gravel/api/status.py
src/gravel/controllers/gstate.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/devices.py
src/gravel/controllers/resources/inventory.py
src/gravel/controllers/resources/status.py
src/gravel/controllers/resources/storage.py
src/gravel/controllers/services.py
src/gravel/tests/conftest.py
src/gravel/tests/unit/cephadm/test_cephadm.py
src/gravel/tests/unit/controllers/orch/test_ceph.py
src/gravel/tests/unit/controllers/test_config.py
src/gravel/tests/unit/controllers/test_gstate.py
src/gravel/tests/unit/controllers/test_services.py

This refactor instantiates Tickers (ie long running sub processes that
persist across requests+sessions) as part of the app. It stores them
inside FastAPI's `app.state`, which in turn is available on FastAPI's
`Request` object.
I could not find the most "FastAPI way" of doing this. From my reading, the way we were handling state with module level globals is generally the approach that FastAPI takes. This has some difficult draw backs with mocking and testing, not to mention potential complications on instantiating multiple redundant (or even conflicting) instances, and the general developer confusion about what they are accessing. There is some good discussion on it here: https://github.com/tiangolo/fastapi/issues/81
The solution, as describe in the commit above, is to create all the …

Reduce usage of module level globals

---

images/microOS/config.xml
src/gravel/controllers/config.py
src/gravel/controllers/nodes/mgr.py

* reduces the number of system (e.g. rpm) dependencies for the image
* consistent with platforms such as CoreOS and k8s
* could potentially make the orchestration of etcd a bit easier later down the road ...
---
<details>
</details>

gravel: run etcd within a container

---

src/gravel/api/bootstrap.py
src/gravel/api/local.py
src/gravel/controllers/config.py
src/gravel/controllers/errors.py
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/errors.py
src/gravel/controllers/nodes/etcd.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/devices.py
src/gravel/controllers/resources/status.py
src/gravel/controllers/resources/storage.py
src/gravel/controllers/utils.py

This is just a first pass towards a proper rework of the initial node deployment workflow.
Right now we're simply spinning-off a bit of the bootstrap and join code to a `deployment.py` module.
I'm going to do this in batches to make it easier to review.

gravel: rework, cleanup node deployment

---

src/aquarium.py
src/gravel/api/local.py
src/gravel/cephadm/cephadm.py
src/gravel/controllers/nodes/etcd.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/devices.py
src/gravel/controllers/resources/inventory.py
src/gravel/controllers/resources/status.py
src/gravel/controllers/resources/storage.py
src/gravel/tests/conftest.py

Second installment in the "let's rework the backend's init workflow" series.
In this episode we are dropping the `prestart` state and replacing it with a `prepare`, which will obtain container images and process the initial inventory; then we add a new state, `available`, which means the node is now available to serve a bootstrap or a join request.
This difference is mostly for the benefit of the backend, so we can keep track where we are instead of cramming everything into the same state. Additionally, the frontend will be able to distinguish between these two states and inform the user in case we're still preparing the node.
On a tangential topic, we're also now disabling the dashboard and the monitoring stack on bootstrap. We don't use it, and makes it easier to figure out which …

gravel: init stage rework (phase 2)

---

src/gravel/controllers/gstate.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/inventory.py

The quicker we obtain the inventory, less time the user is waiting for the node to become available to bootstrap.
By fiddling with the tick interval and calling back on the subscribe as soon as possible, we're reducing this time from about 30-60 seconds, to a handful of seconds.
This actually resolves #328 

gravel: make obtaining inventory quicker on node start

---

src/glass/src/app/pages/install-wizard-page/install-wizard-page.component.html

On other installer pages we are using an mat-icon-button for the `Back` button, because of that the wizard needs to be adapted to be consistent.
---
<details>
</details>

glass: Use icon buttons

---

doc/from-zero-to-hacking.md

The names of the deployed nodes are no longer `node01` and `node02` but `node1` and `node2`.
Also the https://github.com/aquarist-labs/aquarium/blob/main/tests/vagrant/README.md seems to be outdated as well and I'm wondering what to do about it. I do have the feeling it will be more or less a duplicated subset of `from-zero-to-hacking.md`. I'm wondering if we can just remove the content of https://github.com/aquarist-labs/aquarium/blob/main/tests/vagrant/README.md .
---
<details>
</details>

doc: fix node names

---

tools/aqrdev
tools/libaqr/deployment.py
tools/libaqr/errors.py
tools/libaqr/misc.py
tools/libaqr/vagrant.py

This patchset focus on reworking `aqrdev`'s internal organization, splitting off auxiliary functions into a separate module to then be consumed by upcoming work, reducing the amount of code in the one single file we had.

aqrdev: rework internal structure

---

tools/build-image.sh
tools/setup-dev.sh

When doing a build on an opensuse tumbleweed cloud image, the locale
isn't already set correctly for kiwi (see
https://www.suse.com/support/kb/doc/?id=000019958).
kiwi also needed dosfstools at some point. I'm not sure why, but
installing it unblocked me.
Signed-off-by: Joshua Hesketh <josh@nitrotech.org>

build: Fix opensuse builds on cloud images

---

tests/examples/test_libaqr.py
tests/suites/smoke/test_api_bootstrap.py
tests/suites/smoke/test_api_orch.py
tools/aqrdev
tools/aqrtest.py
tools/libaqr/deployment.py
tools/libaqr/errors.py
tools/libaqr/http.py
tools/libaqr/images.py
tools/libaqr/misc.py
tools/libaqr/runner.py
tools/libaqr/suites.py
tools/libaqr/testing.py
tools/libaqr/vagrant.py

With this we are introducing a new script, `aqrtest.py`, which will run tests within the `tests/suites/` directory against a live vagrant cluster.
Tests are organized in Test Cases, which can be one or contain multiple Case Units. Each Test Case will declare its requirements, based on which the cluster will be deployed.
~This is still on-going work, and~ I'm looking for feedback.
**Note:** even after merge, we can't immediately make this the default on all PRs because it is expected that a lot of the API tests are going to fail. The API needs to be fixed before we can enable automatic checks as merging criteria.

aqrtest: functional test battery against a live cluster

---

src/gravel/cephadm/cephadm.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/orch/ceph.py
src/gravel/tests/conftest.py
src/gravel/tests/unit/controllers/orch/test_ceph.py

set the osd pool size to 3 when more than 3 nodes are present,
otherwise, (re)set the pool size to 2.
- sets the `osd_pool_default_size` for newly created pools
- adjusts the pool size for any other existing pool(s):
- if not managed by an aquarium service
- if not a user-defined pool
Resolves: #404
---
<details>
</details>

gravel: osd pool default size

---

images/builder/Dockerfile
images/builder/README.md
tools/autobuilder.sh
tools/build-image.sh

This patchset introduces a container image able to automatically build a source tree upon being run.
Additionally, allows the user to configure the source repository's root directory and the builds' output directory via the CLI to the existing `build-image.sh` script.
This is mighty useful to build images in one go without having to 1) do a lot of things, and 2) require root. Also allows for better automation.

images/builder: Build an image in one go with containers

---

src/gravel/cephadm/cephadm.py

The config parser expects a blank line before EOF, otherwise it will
fail to parse the user-supplied config.
This is required as a prerequisite to merge #513 
Signed-off-by: Joao Eduardo Luis <joao@suse.com>

gravel: cephadm/bootstrap: parser expects line before EOF

---

images/microOS/root/etc/containers/storage.conf
src/gravel/api/nodes.py
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/disks.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/nodes/systemdisk.py
src/gravel/controllers/utils.py
src/gravel/tests/unit/controllers/nodes/data/disks_local_inventory.json
src/gravel/tests/unit/controllers/nodes/data/disks_local_inventory_with_ssd.json
src/gravel/tests/unit/controllers/nodes/data/disks_single_volume.json
src/gravel/tests/unit/controllers/nodes/test_deployment.py
src/gravel/tests/unit/controllers/nodes/test_disks.py

This PR does not propose itself to address all the needs for a system disk, nor the full impact of having, creating, or maintaining one. Instead, this is the building block on which further work should be performed.
Consider this PR as a draft, open for comments.
Consider tests to be an on-going task.
* generate a potential solution for disk usage from the available devices, including a candidate device for system disk.
* create a system disk on initial node deploy.
* mount aquarium-specific directories from the system disk to the running system's root tree, either by overlaying them or bind mounting them.
* mount the system disk on boot, should it be present.
* do all of the above for a node joining the system.
* present the user with the generated solution, and allow them to have an …

gravel: create system disk on initial deployment

---

tools/libaqr/deployment.py

If vagrant up fails when trying to start a deployment status is not
checked. Thif patch address this issue.
---
<details>
</details>

tools/libaqr: check deployment start error

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.spec.ts
src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.ts
src/glass/src/app/shared/components/declarative-form/declarative-form.component.html

In the install wizard error notifications are displayed twice, the first notification is shown automatically by the HTTP error interceptor and the second one by the install wizard. To prevent the duplicate notification 'preventDefault' must be called.
Additionally a HTML linter error has been fixed.
---
<details>
</details>

glass: Display error notifications only once

---

src/gravel/controllers/nodes/mgr.py

Closes the hole of CVE-2021-20288.
Resolves: #450 

gravel: do not allow insecure global id in Ceph

---

Makefile
doc/dev/gravel/systemd-boot.md
images/aquarium/config.sh
images/aquarium/root/usr/lib/systemd/system/aquarium-boot.service
src/boot/aqrbootsetup.sh
src/gravel/controllers/nodes/etcd.py
src/gravel/controllers/nodes/mgr.py

This patchset makes the image recognize the system disk on boot, and overlays or bind mounts the right directories inn the right places.

gravel: handle systemdisk on boot

---

src/glass/src/app/core/dashboard/dashboard.module.ts
src/glass/src/app/core/dashboard/widgets/allocations-dashboard-widget/allocations-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/capacity-dashboard-widget/capacity-dashboard-widget.component.ts
src/glass/src/app/core/dashboard/widgets/services-capacity-dashboard-widget/services-capacity-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-utilization-dashboard-widget/services-utilization-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/services-utilization-dashboard-widget/services-utilization-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/services-utilization-dashboard-widget/services-utilization-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/services-utilization-dashboard-widget/services-utilization-dashboard-widget.component.ts
src/glass/src/app/pages/dashboard-page/dashboard-page.component.html
src/glass/src/app/pages/dashboard-page/dashboard-page.component.ts

- Rename existing 'Services Capacity' widget to 'Services Utilization'
- Add new 'Services Capacity' widget
- Hide legends in both widgets, display y-axis instead
Fixes: https://github.com/aquarist-labs/aquarium/issues/486
---
<details>
</details>

glass: Add capacity dashboard widget

---

tools/setup-dev.sh

The nodejs 15.x is deprecated and not actively supported anymore.
It is kindly adviced to switch to any of 12.x, 14.x or 16.x
---
<details>
</details>

tools/setup-dev: use nodejs 16.x instead of 15.x

---

images/aquarium/config.sh
images/aquarium/config.xml

As of today, for some reason, the vagrant image ceased to work due to
the 'vagrant' user being passwordless. To address this, let's create the
user in the config.xml kiwi file, with a default password of 'vagrant',
but only for images being built for Vagrant.
---
<details>
</details>

images/aquarium: add password to vagrant user

---

images/aquarium/config.xml

The image stopped working at some point in the last few days. Turns out `wicked` was no longer being installed. My suspicion is that we were installing it as a dependency for something, and said dependency was dropped.

images: fix network not starting on boot

---

src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.spec.ts
src/glass/src/app/pages/install-wizard/install-create-wizard-page/install-create-wizard-page.component.ts
src/glass/src/app/pages/install-wizard/install-join-wizard-page/install-join-wizard-page.component.ts
src/glass/src/app/shared/services/api/nodes.service.spec.ts
src/glass/src/app/shared/services/api/nodes.service.ts
src/gravel/api/nodes.py
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/mgr.py
src/gravel/tests/unit/controllers/nodes/test_deployment.py

We are now passing the user-specified hostname as parameters to the deploy and join endpoints, so we can set the hostname as part of a node's deployment process.
We are also removing the endpoint that allows to set the hostname because we suspect changing a hostname after a node has been deployed will not be a trivial task, and we currently have no other use for this endpoint.
~Depends on #581~

gravel: pass hostname as parameters to deploy & join (part 1)

---

images/aquarium/config.xml
src/boot/aqrbootsetup.sh
src/gravel/api/orch.py
src/gravel/api/services.py
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/nodes/systemdisk.py
src/gravel/controllers/orch/ceph.py
src/gravel/controllers/orch/orchestrator.py
src/gravel/tests/unit/controllers/nodes/test_deployment.py
src/gravel/tests/unit/controllers/orch/data/device_ls_not_available.json
src/gravel/tests/unit/controllers/orch/test_orchestrator.py
src/requirements-test.txt
src/requirements.txt

With this patch set we now support system disk creation on a joining node, as well as assimilating devices individually (instead of a blanket `all available`), both on a seed node and on a joining node.
~This patch set depends on merging #575  and  #581~

gravel: support system disk on joining node, assimilate devices individually (part 2)

---

images/aquarium/config.xml
images/aquarium/root/etc/sysconfig/network/ifcfg-eth0
images/aquarium/root/etc/udev/rules.d/10-aqr-nics.rules
images/aquarium/root/usr/lib/systemd/system/aquarium-boot.service
src/boot/add-nic.sh
src/boot/aqrbootsetup.sh
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/orch/orchestrator.py
src/gravel/tests/unit/controllers/nodes/test_deployment.py

In this patch set we cover quite a few things, which presented themselves while running on real hardware:
- network interfaces are now populated from udev rules, allowing us to support any number of NICs, and will be configured to use dhcp by default so we can access the server and (eventually) further configure the network;
- we now wait for the seed host to be added to the underlying Ceph cluster before we wait for disk devices to be assimilated -- running on real hardware made this behavior visible, while it doesn't show up while running on Vagrant;
- we now wait for devices to be probed on the host before checking whether they are still available -- real hardware will take a lot longer to probe than the vagrant machines, especially with more disks;
- we had to change the …

aquarium: address multiple issues when running on real hardware

---

src/gravel/tests/unit/controllers/nodes/test_mgr.py
src/gravel/tests/unit/controllers/test_auth.py

We need to account for the new user management code that exists and is
called during the NodeMgr's deploy().

gravel/tests: nodes/mgr: fix deploy test

---

src/gravel/api/user.py
tests/suites/smoke/test_api_user.py

Handle this behaviour completely in the backend, no need to do any checks in the frontend.
Fixes: https://github.com/aquarist-labs/aquarium/issues/607
---
<details>
</details>

gravel/glass: user management - prevent the current user from disabling himself

---

src/gravel/controllers/orch/nfs.py

I received an validation error: 
```pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[List[gravel.controllers.orch.nfs.NFSDaemonModel]] __root__```
```value is not a valid list (type=type_error.list)```
when calling GET `/nfs/service/{service_id}`.
I'm not fully sure if it is what the endpoint is suppose to return. But at least it fixes the error 500 returned by the API currently.
If the return value is incorrect now, just let me know and I'll adapt the PR accordingly.
---
<details>
</details>

gravel: fix NFS info to reflect Ceph cmd return

---

tools/run_aquarium.sh

tools: Add the missing --port option to the usage/help text

---

tools/aqrdev
tools/libaqr/deployment.py

The --trace options is an alternative to --debug but
it also includes module name and line number where
the message is produced as well as function name.
---
<details>
</details>

tools/aqrdev: add --trace option for detailed logging

---

.github/workflows/glass-unit-tests.yml
src/glass/package-lock.json
src/glass/package.json
tools/setup-dev.sh

Currently npm install is used which isn't correct as it doesn't
consider the versions mentioned in the `package-lock.json`,
`npm ci` however does.
This also updates the git workflow in order to test the right command.
---
Fundamental changes in the lock file in order to use node 14 and older and not only 16.
This change also updates the packages.
---
<details>
</details>

tools: Use npm ci in setup-dev.sh

---

src/glass/src/app/core/top-bar/top-bar.component.html

Prevent the ngbDropdownMenu from running out of screen
---
<details>
</details>

glass: fix top bar

---

src/requirements.txt

As title, kiwi update a new release the old version build images are no longer exist. So I need to update the version number in order to allow the build to work for all the platforms.  
Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>

[tool] Update kiwi and box version requirement to update the build

---

tools/libaqua/cli.py
tools/libaqua/deployment.py
tools/libaqua/vagrant.py

This is helpful if aqrdev is used inside a script where user approval
just delays.
---
<details>
</details>

tools: Adds force option on box destroy

---

src/glass/src/app/shared/components/datatable/datatable.component.html
src/glass/src/app/shared/components/datatable/datatable.component.scss
src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts

---
glass: Use bootstrap in datatable action dropdown
---
glass: Cache shown table data
If `data` is updated and the resulting shown page won't change
the current seen table, the table itself will not be re-rendered
as `filteredData` will still result the same object as before.
---
<details>
</details>

glass: Use bootstrap in datatable action dropdown

---

src/gravel/api/__init__.py

Fixes: https://github.com/aquarist-labs/aquarium/issues/657
---
<details>
</details>

gravel: A failing JWT authentication should log out the user

---

src/glass/cypress/integration/dive_into_aquarium.js

This adds a bunch of ".should('be.visible')" calls to slow cypress
down a bit, and wait for each page of the setup wizard to render
completely before trying to hit the Next/Install buttons.
---
<details>
</details>

glass: make cypress wait for elements to be visible

---

.gitignore
.wasser/config.yaml
doc/from-zero-to-hero.md
src/requirements.txt
tools/requirements.txt
tools/run_aquarium.sh
tools/setup-dev.sh

Because setup-dev.sh is ran on the developers machine, it is not okay
to use the system packages which may conflict with the requirements.txt
aquarium is trying to install (for example, the system packages may
already supply a dependency which will mean that pip will then not
install it into the venv).
Instead we should ensure the venv is created without system packages.
This is what is eventually copied into the virtual machine. Before we
copy it in though we need to re-enable the system packages for
librados to work, so we do that manually with sed.
Signed-off-by: Joshua Hesketh <josh@nitrotech.org>

deps: Fix potential dependency issues on dev machines

---

src/glass/src/app/pages/hosts-page/hosts-page.component.ts
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/services/api/auth.service.ts

- Make sure progress bar is stopped in case of an API call error
- Use finalize() instead of tap() on sign out to make sure session is cleared in case of an API call error
---
<details>
</details>

glass: Various improvements

---

src/glass/src/app/shared/components/language-button/language-button.component.html

The languages dropdown is cut in the installer layout. Fix the dropdown in order to show the whole menu.
->
---
<details>
</details>

glass: fix languages dropdown list

---

src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.html
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.scss
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.spec.ts
src/glass/src/app/core/dashboard/widgets/sys-info-dashboard-widget/sys-info-dashboard-widget.component.ts
src/glass/src/app/shared/components/widget/widget.component.scss

The chart in the system information widget is rendered too big.
---
<details>
</details>

glass: Fix widget render issue

---

src/gravel/controllers/config.py
src/gravel/tests/unit/controllers/test_config.py

By specifying
```
AQUARIUM_REGISTRY_URL=<URL>
AQUARIUM_REGISTRY_IMAGE=<NAME>
AQUARIUM_REGISTRY_SECURE=<true|false>
```
as environment variables, we can specify a custom registry directly to
the aquarium service without having to configure it through the UI or
the API.
Extremely helpful during development.

gravel: allow passing custom registry as env vars

---

src/gravel/controllers/containers.py
src/gravel/controllers/nodes/deployment.py
src/gravel/tests/unit/controllers/nodes/test_deployment.py
src/gravel/tests/unit/controllers/test_containers.py
src/requirements-test.txt
src/requirements.txt

With this patch set we now check whether a registry is reachable, and the container image exists at the registry, before allowing the node to deploy.
The major issue with this patch set is that it perpetuates the bad habit of not handling exceptions in an ideal way, conveying to the caller what might be wrong (aside from something being wrong). This, I believe, needs to be addressed as a whole in a future patch set.

gravel: check registry before deployment

---

src/glass/src/app/pages/install-welcome-page/install-welcome-page.component.ts
src/glass/src/app/pages/network-page/network-page.component.ts
src/glass/src/app/pages/users-page/users-page.component.ts
src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts
src/glass/src/app/shared/models/datatable-column.type.ts

Naming this property 'sortable' is more common practice than 'unsortable'. The new name is also more intuitive.
---
<details>
</details>

glass: Rename datatable column property 'unsortable' to 'sortable'

---

src/glass/src/app/shared/components/datatable/datatable.component.spec.ts
src/glass/src/app/shared/components/datatable/datatable.component.ts

Set it to 1 explicitely, otherwise the action column will consume too much space.
---
<details>
</details>

glass: Set correct width of the datatable action column

---

images/builder/Dockerfile

Make sure we use the latest Kiwi version (which includes a fix to workaround the problem of aquarist-labs#738).
Fixes: https://github.com/aquarist-labs/aquarium/issues/738
---
<details>
</details>

tools: Fix Kiwi issue when using a container to build the Vagrant image

---

images/aquarium/config.xml
src/aquarium.py
src/gravel/api/local.py
src/gravel/api/nodes.py
src/gravel/controllers/config.py
src/gravel/controllers/gstate.py
src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/mgr.py
src/gravel/controllers/resources/network.py
src/gravel/tests/conftest.py
src/gravel/tests/unit/controllers/network/data/config
src/gravel/tests/unit/controllers/network/data/ifcfg-eth0
src/gravel/tests/unit/controllers/network/test_network.py
src/gravel/tests/unit/controllers/nodes/test_mgr.py
src/requirements-test.txt
src/requirements.txt

This adds the ability for gravel to read and write network interface configuration, nameservers and routes.  We've added an /api/local/network/config endpoint.  GET this, and you'll retrieve a dict of interfaces, a list of nameservers and a list of static routes.  In the simple case for a single NIC that's configured for DHCP, this'll give you:
```json
{
"interfaces": {
"eth0": {
"name": "eth0",
"config": {
"bootproto": "dhcp",
"ipaddr": "",
"bonding_slaves": []
}
}
},
"nameservers": [],
"routes": []
}
```
POST back to that same URL to apply a different config.  The config exposed is deliberately a subset of what's possible to specify in /etc/sysconfig/network/{config,routes,ifcfg-*,ifroute-*} files.  For 'interfaces', bootproto can be either "dhcp" or "static".  If it's "static", you …

gravel: add network controller and API endpoints

---

src/gravel/controllers/nodes/deployment.py
src/gravel/controllers/nodes/systemdisk.py
src/gravel/tests/unit/controllers/nodes/data/mounts_silly.raw
src/gravel/tests/unit/controllers/nodes/test_systemdisk.py

This is preparatory clean up work for a bigger cleanup and rework of how we deploy the system. In part to account for an inevitable change in how we install the system, but mostly (and more pressing) to better handle error states.

gravel: clean up systemdisk

---

src/glass/src/app/shared/components/datatable/datatable.component.html

This default cell template will display a tooltip which is useful if the cell content overlaps and is hidden via CSS 'overflow-x'.
---
<details>
</details>

Use default datatable cell template for all columns that have not defined a specific template

---

src/gravel/controllers/inventory/disks.py

gravel: ignore cdrom on disk inventory
